package htSpike.test;
// Generated by ComTest BEGIN
import htSpike.*;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Ottelut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.23 12:46:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OttelutTest {



  // Generated by ComTest BEGIN
  /** testLisaa31 */
  @Test
  public void testLisaa31() {    // Ottelut: 31
    Ottelut ottelut = new Ottelut(); 
    Ottelu peli1 = new Ottelu(); 
    Ottelu peli2 = new Ottelu(); 
    Ottelu peli3 = new Ottelu(); 
    Ottelu peli4 = new Ottelu(); 
    Ottelu peli5 = new Ottelu(); 
    assertEquals("From: Ottelut line: 40", 0, ottelut.getOttelulista().size()); 
    ottelut.lisaa(peli1); 
    ottelut.lisaa(peli2); 
    ottelut.lisaa(peli3); 
    Ottelu eka = ottelut.getOttelulista().get(0); 
    assertEquals("From: Ottelut line: 45", 3, ottelut.getOttelulista().size()); 
    ottelut.lisaa(peli4); 
    ottelut.lisaa(peli5); 
    assertEquals("From: Ottelut line: 48", 3, ottelut.getOttelulista().size()); 
    assertEquals("From: Ottelut line: 49", ottelut.getOttelulista().get(2), eka); 
  } // Generated by ComTest END
}