package htSpike.test;
// Generated by ComTest BEGIN
import htSpike.Pelaaja;
import htSpike.Ottelu;
import fi.jyu.mit.ohj2.Suuntaaja;
import htSpike.*;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Ottelu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.23 18:10:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OtteluTest {



  // Generated by ComTest BEGIN
  /** testToString126 */
  @Test
  public void testToString126() {    // Ottelu: 126
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    Pelaaja simo4 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    simo4.luojotain(); 
    int[] pelaajat = { simo1.getId(), simo2.getId(), simo3.getId(), simo4.getId()} ; 
    int[] tulos = { 21,15,15,21,21,15} ; 
    Ottelu ottelu = new Ottelu(pelaajat, tulos); 
    assertEquals("From: Ottelu line: 140", "1|2|3|4|21|15|15|21|21|15", ottelu.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVoittaja154 */
  @Test
  public void testVoittaja154() {    // Ottelu: 154
    int[] parit = { 1,2,3,4} ; 
    int[] pisteet = { 21,15,14,21,21,16} ; 
    Ottelu ottelu = new Ottelu(parit, pisteet); 
    assertEquals("From: Ottelu line: 160", 1, ottelu.voittaja()); 
    int[] parit2 = { 1,2,3,4} ; 
    int[] pisteet2 = { 15,21,21,15,13,21} ; 
    Ottelu ottelu2 = new Ottelu(parit2, pisteet2); 
    assertEquals("From: Ottelu line: 164", 2, ottelu2.voittaja()); 
    int[] parit3 = { 1,2,3,4} ; 
    int[] pisteet3 = { 21,15,14,21,0,0} ; 
    Ottelu ottelu3 = new Ottelu(parit3, pisteet3); 
    assertEquals("From: Ottelu line: 168", -1, ottelu3.voittaja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta189 */
  @Test
  public void testTulosta189() {    // Ottelu: 189
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    int[] pelaajat = { 1,2,3,4} ; 
    int[] tulos = { 21,13,12,21,21,15} ; 
    Ottelu ottelu = new Ottelu(pelaajat, tulos); 
    ottelu.tulosta(System.out); 
    String tulostus = "1&2 VS 3&4\n" +
    "Erä 1: 21 - 13\n" +
    "Erä 2: 12 - 21\n" +
    "Erä 3: 21 - 15\n" +
    "Pari 1 voitti!\n"; 
    assertEquals("From: Ottelu line: 201", null, so.ero(tulostus)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse234 */
  @Test
  public void testParse234() {    // Ottelu: 234
    String s = "1|2|3|4|21|15|21|15|0|0"; 
    Ottelu ottelu = new Ottelu(); 
    ottelu.parse(s); 
    assertEquals("From: Ottelu line: 240", 1, ottelu.voittaja()); 
    assertEquals("From: Ottelu line: 241", "1|2|3|4|21|15|21|15|0|0", ottelu.toString());
  } // Generated by ComTest END
}