package htSpike.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import htSpike.*;
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Ottelut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 14:59:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OttelutTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta35 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta35() throws IOException {    // Ottelut: 35
    VertaaTiedosto.kirjoitaTiedosto("comtestTied/ottelut.dat",
    "1|2|3|4|1|0|1|0|1|0\n"+
    "1|2|3|4|1|0|1|0|1|1\n"+
    "1|2|3|4|1|0|1|0|1|2\n"); 
    Ottelut ottelut = new Ottelut(); 
    ottelut.lueTiedostosta("comtestTied"); 
    ArrayList<Ottelu> lista = ottelut.getOtteluLista(); 
    assertEquals("From: Ottelut line: 50", "1|2|3|4|1|0|1|0|1|0", lista.get(0).toString());
    assertEquals("From: Ottelut line: 51", "1|2|3|4|1|0|1|0|1|1", lista.get(1).toString());
    assertEquals("From: Ottelut line: 52", "1|2|3|4|1|0|1|0|1|2", lista.get(2).toString());
    VertaaTiedosto.tuhoaTiedosto("comtestTied/ottelut.dat"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna81 
   * @throws IOException when error
   */
  @Test
  public void testTallenna81() throws IOException {    // Ottelut: 81
    Ottelu ottelu1 = new Ottelu(new int[]{1,2,3,4}, new int[]{1,0,1,0,1,0}); 
    Ottelu ottelu2 = new Ottelu(new int[]{1,2,3,4}, new int[]{1,0,1,0,1,0}); 
    Ottelu ottelu3 = new Ottelu(new int[]{1,2,3,4}, new int[]{1,0,1,0,1,0}); 
    Ottelut ottelut = new Ottelut(); 
    ottelut.lisaa(ottelu1); 
    ottelut.lisaa(ottelu2); 
    ottelut.lisaa(ottelu3); 
    String tulos =
    "1|2|3|4|1|0|1|0|1|0\n"+
    "1|2|3|4|1|0|1|0|1|0\n"+
    "1|2|3|4|1|0|1|0|1|0\n"; 
    ottelut.tallenna("comtestTied"); 
    assertEquals("From: Ottelut line: 100", null, VertaaTiedosto.vertaaFileString("comtestTied/ottelut.dat", tulos)); 
    VertaaTiedosto.tuhoaTiedosto("comtestTied/ottelut.dat"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa130 */
  @Test
  public void testLisaa130() {    // Ottelut: 130
    Ottelut ottelut = new Ottelut(); 
    Ottelu peli1 = new Ottelu(); 
    Ottelu peli2 = new Ottelu(); 
    Ottelu peli3 = new Ottelu(); 
    Ottelu peli4 = new Ottelu(); 
    Ottelu peli5 = new Ottelu(); 
    assertEquals("From: Ottelut line: 139", 0, ottelut.getOtteluLista().size()); 
    ottelut.lisaa(peli1); 
    ottelut.lisaa(peli2); 
    ottelut.lisaa(peli3); 
    Ottelu eka = ottelut.getOtteluLista().get(0); 
    assertEquals("From: Ottelut line: 144", 3, ottelut.getOtteluLista().size()); 
    ottelut.lisaa(peli4); 
    ottelut.lisaa(peli5); 
    assertEquals("From: Ottelut line: 147", 5, ottelut.getOtteluLista().size()); 
    assertEquals("From: Ottelut line: 148", ottelut.getOtteluLista().get(2), eka); 
  } // Generated by ComTest END
}