package htSpike.test;
// Generated by ComTest BEGIN
import htSpike.Ottelu;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Ottelu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.22 20:34:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OtteluTest {



  // Generated by ComTest BEGIN
  /** testVoittaja122 */
  @Test
  public void testVoittaja122() {    // Ottelu: 122
    int[] parit = { 1,2,3,4} ; 
    int[] pisteet = { 21,15,14,21,21,16} ; 
    Ottelu ottelu = new Ottelu(parit, pisteet); 
    assertEquals("From: Ottelu line: 128", 1, ottelu.voittaja()); 
    int[] parit2 = { 1,2,3,4} ; 
    int[] pisteet2 = { 15,21,21,15,13,21} ; 
    Ottelu ottelu2 = new Ottelu(parit2, pisteet2); 
    assertEquals("From: Ottelu line: 132", 2, ottelu2.voittaja()); 
    int[] parit3 = { 1,2,3,4} ; 
    int[] pisteet3 = { 21,15,14,21,0,0} ; 
    Ottelu ottelu3 = new Ottelu(parit3, pisteet3); 
    assertEquals("From: Ottelu line: 136", -1, ottelu3.voittaja()); 
  } // Generated by ComTest END
}