package htSpike.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import htSpike.*;
import htSpike.Pelaajat;
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Pelaajat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 15:16:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testTallenna29 
   * @throws IOException when error
   */
  @Test
  public void testTallenna29() throws IOException {    // Pelaajat: 29
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.parse("1|Heppu1|1|1|Oikea|Nainen"); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("2|Heppu2|2|2|Vasen|Nainen"); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("3|Heppu3|3|3|Oikea|Mies"); 
    Pelaajat pelaajat = new Pelaajat(); 
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.lisaa(pelaaja3); 
    String tulos =
    "1|Heppu1|1|1|Oikea|Nainen\n"+
    "2|Heppu2|2|2|Vasen|Nainen\n"+
    "3|Heppu3|3|3|Oikea|Mies\n"; 
    pelaajat.tallenna("comtestTied"); 
    assertEquals("From: Pelaajat line: 51", null, VertaaTiedosto.vertaaFileString("comtestTied/pelaajat.dat", tulos)); 
    VertaaTiedosto.tuhoaTiedosto("comtestTied/pelaajat.dat"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa71 */
  @Test
  public void testLisaa71() {    // Pelaajat: 71
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.luojotain(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.luojotain(); 
    assertEquals("From: Pelaajat line: 79", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja1); 
    assertEquals("From: Pelaajat line: 81", pelaaja1, pelaajat.annaPelaaja(0)); 
    assertEquals("From: Pelaajat line: 82", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja2); 
    assertEquals("From: Pelaajat line: 84", pelaaja2, pelaajat.annaPelaaja(1)); 
    assertEquals("From: Pelaajat line: 85", 2, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPelaaja133 */
  @Test
  public void testGetPelaaja133() {    // Pelaajat: 133
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    pelaajat.lisaa(simo1); 
    pelaajat.lisaa(simo2); 
    pelaajat.lisaa(simo3); 
    pelaajat.tulosta(); 
    assertEquals("From: Pelaajat line: 146", simo1, pelaajat.getPelaaja(1)); 
    assertEquals("From: Pelaajat line: 147", null, pelaajat.getPelaaja(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta166 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta166() throws IOException {    // Pelaajat: 166
    VertaaTiedosto.kirjoitaTiedosto("comtestTied/pelaajat.dat",
    "1|Heppu1|1|1|Oikea|Nainen\n"+
    "2|Heppu2|2|2|Vasen|Nainen\n"+
    "3|Heppu3|3|3|Oikea|Mies\n"); 
    Pelaajat pelaajat = new Pelaajat(); 
    pelaajat.lueTiedostosta("comtestTied"); 
    assertEquals("From: Pelaajat line: 180", "1|Heppu1|1|1|Oikea|Nainen", pelaajat.annaPelaaja(0).toString()); 
    assertEquals("From: Pelaajat line: 181", "2|Heppu2|2|2|Vasen|Nainen", pelaajat.annaPelaaja(1).toString()); 
    assertEquals("From: Pelaajat line: 182", "3|Heppu3|3|3|Oikea|Mies", pelaajat.annaPelaaja(2).toString()); 
    VertaaTiedosto.tuhoaTiedosto("comtestTied/pelaajat.dat"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista209 */
  @Test
  public void testPoista209() {    // Pelaajat: 209
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    pelaajat.lisaa(simo1); 
    pelaajat.lisaa(simo2); 
    pelaajat.lisaa(simo3); 
    int id = simo2.getId(); 
    assertEquals("From: Pelaajat line: 223", 3, pelaajat.getLkm()); 
    pelaajat.poista(simo2); 
    assertEquals("From: Pelaajat line: 225", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 226", 3, pelaajat.annaPelaaja(1).getId()); 
    assertEquals("From: Pelaajat line: 227", null, pelaajat.getPelaaja(id)); 
  } // Generated by ComTest END
}