package htSpike.test;
// Generated by ComTest BEGIN
import htSpike.Pelaajat;
import htSpike.*;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Pelaajat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.25 10:04:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa50 */
  @Test
  public void testLisaa50() {    // Pelaajat: 50
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.luojotain(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.luojotain(); 
    assertEquals("From: Pelaajat line: 58", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja1); 
    assertEquals("From: Pelaajat line: 60", pelaaja1, pelaajat.annaPelaaja(0)); 
    assertEquals("From: Pelaajat line: 61", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja2); 
    assertEquals("From: Pelaajat line: 63", pelaaja2, pelaajat.annaPelaaja(1)); 
    assertEquals("From: Pelaajat line: 64", 2, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPelaaja112 */
  @Test
  public void testGetPelaaja112() {    // Pelaajat: 112
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    pelaajat.lisaa(simo1); 
    pelaajat.lisaa(simo2); 
    pelaajat.lisaa(simo3); 
    pelaajat.tulosta(); 
    assertEquals("From: Pelaajat line: 126", simo1, pelaajat.getPelaaja(1)); 
    assertEquals("From: Pelaajat line: 127", null, pelaajat.getPelaaja(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista166 */
  @Test
  public void testPoista166() {    // Pelaajat: 166
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    pelaajat.lisaa(simo1); 
    pelaajat.lisaa(simo2); 
    pelaajat.lisaa(simo3); 
    int id = simo2.getId(); 
    assertEquals("From: Pelaajat line: 180", 3, pelaajat.getLkm()); 
    pelaajat.poista(simo2); 
    assertEquals("From: Pelaajat line: 182", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 183", 3, pelaajat.annaPelaaja(1).getId()); 
    assertEquals("From: Pelaajat line: 184", null, pelaajat.getPelaaja(id)); 
  } // Generated by ComTest END
}