package htSpike.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import htSpike.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.19 09:39:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {


  // Generated by ComTest BEGIN
  /** testToString27 */
  @Test
  public void testToString27() {    // Pelaaja: 27
    Pelaaja simo = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 29", "", simo.toString()); 
  } // Generated by ComTest END
}