package htSpike.test;
import htSpike.Pelaaja;
// Generated by ComTest BEGIN
import htSpike.Pelaajat;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Pelaajat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.19 10:59:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {


  // Generated by ComTest BEGIN
  /** testLisaa19 */
  @Test
  public void testLisaa19() {    // Pelaajat: 19
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.luojotain(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.luojotain(); 
    assertEquals("From: Pelaajat line: 27", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja1); 
    assertEquals("From: Pelaajat line: 29", pelaaja1, pelaajat.annaPelaaja(0)); 
    assertEquals("From: Pelaajat line: 30", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(pelaaja2); 
    assertEquals("From: Pelaajat line: 32", pelaaja2, pelaajat.annaPelaaja(1)); 
    assertEquals("From: Pelaajat line: 33", 2, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPelaaja81 */
  @Test
  public void testGetPelaaja81() {    // Pelaajat: 81
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja simo1 = new Pelaaja(); 
    Pelaaja simo2 = new Pelaaja(); 
    Pelaaja simo3 = new Pelaaja(); 
    simo1.luojotain(); 
    simo2.luojotain(); 
    simo3.luojotain(); 
    pelaajat.lisaa(simo1); 
    pelaajat.lisaa(simo2); 
    pelaajat.lisaa(simo3); 
    pelaajat.tulosta(); 
    pelaajat.getPelaaja(1); 
  } // Generated by ComTest END
}