package htSpike.test;
// Generated by ComTest BEGIN
import htSpike.*;
import static org.junit.Assert.*;
import org.junit.*;
import static htSpike.Pelaaja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.23 17:24:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Pelaaja: 139
    Pelaajat pelaajat = new Pelaajat(); 
    String s = "3|Heppu1|4|38|Oikea|Mies"; 
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse(s); 
    assertEquals("From: Pelaaja line: 146", 3, pelaaja.getId()); 
    pelaajat.lisaa(pelaaja); 
    int n = pelaaja.getId(); 
    pelaaja.parse("" + (n + 20)); 
    pelaaja.luojotain(); 
    assertEquals("From: Pelaaja line: 152", n + 20 + 1, pelaaja.getId()); 
  } // Generated by ComTest END
}