package fxHtSpike.test;
// Generated by ComTest BEGIN
import htSpike.Pelaaja;
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static fxHtSpike.OttelutTuloksetController.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.22 20:32:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OttelutTuloksetControllerTest {


  // Generated by ComTest BEGIN
  /** testKasitteleErat110 */
  @Test
  public void testKasitteleErat110() {    // OttelutTuloksetController: 110
    int[] t1 = kasitteleErat(new String[] { "21-15", "21-15", "21-15"} ); 
    assertEquals("From: OttelutTuloksetController line: 113", "[21, 15, 21, 15, 21, 15]", Arrays.toString(t1)); 
    int[] t2 = kasitteleErat(new String[] { "21-15", "21-15", null} ); 
    assertEquals("From: OttelutTuloksetController line: 115", "[21, 15, 21, 15, 0, 0]", Arrays.toString(t2)); 
    int[] t3 = kasitteleErat(new String[] { "2-1", "", null} ); 
    assertEquals("From: OttelutTuloksetController line: 117", "[2, 1, 0, 0, 0, 0]", Arrays.toString(t3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasitteleParit143 */
  @Test
  public void testKasitteleParit143() {    // OttelutTuloksetController: 143
    Pelaaja heppu1 = new Pelaaja(); 
    Pelaaja heppu2 = new Pelaaja(); 
    Pelaaja heppu3 = new Pelaaja(); 
    Pelaaja heppu4 = new Pelaaja(); 
    heppu1.luojotain(); 
    heppu2.luojotain(); 
    heppu3.luojotain(); 
    heppu4.luojotain(); 
  } // Generated by ComTest END
}