package fxHtSpike.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxHtSpike.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.12 13:19:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testToString24 */
  @Test
  public void testToString24() {    // Pelaaja: 24
    Pelaaja simo = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 26", "", simo.toString()); 
  } // Generated by ComTest END
}